apiVersion: apps/v1
kind: Deployment
metadata:
  name: morphic-web
spec:
  template:
    spec:
      containers:
      - name: morphic-web
        env:
          - name: SERVICE_URL
            value: "https://api.morphic.dev/"
          - name: RECAPTCHA_KEY
            value: "6Lc1hfsUAAAAAGFReCJUUva4LHF30XG5pIoJr2Nl"

          - name: MORPHIC_WINDOWS_DOWNLOAD_URL
            value: "https://d23vryjv7k8eyb.cloudfront.net/win/x64/stable/MorphicSetup-v1.0.21042.2.msi"  # scaffold:update-env-var:MORPHIC_WINDOWS_DOWNLOAD_URL
          - name: MORPHIC_WINDOWS_APPCAST_URL
            value: "https://d23vryjv7k8eyb.cloudfront.net/win/x64/stable/MorphicSetup-v1.0.21042.2.appcast.xml"  # scaffold:update-env-var:MORPHIC_WINDOWS_APPCAST_URL

          - name: MORPHIC_WINDOWS_BETA_DOWNLOAD_URL
            value: "https://d23vryjv7k8eyb.cloudfront.net/win/x64/edge/MorphicSetup-v1.3.21144.2.msi"  # scaffold:update-env-var:MORPHIC_WINDOWS_BETA_DOWNLOAD_URL
          - name: MORPHIC_WINDOWS_BETA_APPCAST_URL
            value: "https://d23vryjv7k8eyb.cloudfront.net/win/x64/edge/MorphicSetup-v1.3.21144.2.appcast.xml"  # scaffold:update-env-var:MORPHIC_WINDOWS_BETA_APPCAST_URL
                   
          - name: MORPHIC_MAC_DOWNLOAD_URL
            value: "https://d23vryjv7k8eyb.cloudfront.net/osx/edge/Morphic-v1.21047.8.pkg"  # scaffold:update-env-var:MORPHIC_MAC_DOWNLOAD_URL
          - name: MORPHIC_MAC_APPCAST_URL
            value: "https://d23vryjv7k8eyb.cloudfront.net/osx/edge/Morphic-v1.21047.8.appcast.xml"  # scaffold:update-env-var:MORPHIC_MAC_APPCAST_URL

          - name: MORPHIC_MAC_BETA_DOWNLOAD_URL
            value: "https://d23vryjv7k8eyb.cloudfront.net/osx/edge/Morphic-v1.21109.1.pkg"  # scaffold:update-env-var:MORPHIC_MAC_BETA_DOWNLOAD_URL
          - name: MORPHIC_MAC_BETA_APPCAST_URL
            value: "https://d23vryjv7k8eyb.cloudfront.net/osx/edge/Morphic-v1.21109.1.appcast.xml"  # scaffold:update-env-var:MORPHIC_MAC_BETA_APPCAST_URL

          - name: MORPHIC_MAC_COMMUNITY_DOWNLOAD_URL
            value: https://d23vryjv7k8eyb.cloudfront.net/osx/stable/MorphicCommunity-v0.20263.1.dmg

          - name: MORPHIC_WINDOWS_COMMUNITY_DOWNLOAD_URL
            value: https://d23vryjv7k8eyb.cloudfront.net/win/x64/edge/MorphicCommunitySetup-v1.0.20286.1.msi  # scaffold:update-env-var:MORPHIC_WINDOWS_COMMUNITY_DOWNLOAD_URL
          - name: MORPHIC_WINDOWS_COMMUNITY_APPCAST_URL
            value: https://d23vryjv7k8eyb.cloudfront.net/win/x64/edge/MorphicCommunitySetup-v1.0.20286.1.appcast.xml  # scaffold:update-env-var:MORPHIC_WINDOWS_COMMUNITY_APPCAST_URL
          - name: MORPHIC_COMMUNITY_REGISTRATION_URL
            value: "https://community.morphic.dev/#/register"
